import { create } from "zustand";

// Types matching the Go backend models
export interface StatusFile {
  Path: string;
  X: string;
  Y: string;
}

export interface Status {
  Branch: string;
  Upstream: string;
  Ahead: number;
  Behind: number;
  IsClean: boolean;
  Files: StatusFile[];
}

export interface Commit {
  Hash: string;
  Author: string;
  Email: string;
  Message: string;
  Timestamp: string;
  RefNames: string;
}

export interface Branch {
  Name: string;
  Current: boolean;
  Upstream: string;
  Ahead: number;
  Behind: number;
}

export interface FileChange {
  Type: number;
  OldPath: string;
  NewPath: string;
  Additions: number;
  Deletions: number;
  IsBinary: boolean;
  UnifiedDiff: string;
}

export interface Diff {
  Files: FileChange[];
  TotalAdds: number;
  TotalDeletes: number;
}

export interface PRSummary {
  Number: number;
  Title: string;
  State: string;
  Author: string;
  CreatedAt: string;
  UpdatedAt: string;
  IsDraft: boolean;
  Mergeable: string;
  HeadRef: string;
  BaseRef: string;
  Labels: string[];
}

export interface Issue {
  Number: number;
  Title: string;
  State: string;
  Author: string;
  Body: string;
  CreatedAt: string;
  UpdatedAt: string;
  Labels: { Name: string; Color: string }[];
  Assignees: string[];
  Comments: number;
}

export interface Repo {
  Owner: string;
  Name: string;
  FullName: string;
  Description: string;
  Language: string;
  DefaultBranch: string;
  IsPrivate: boolean;
  Stars: number;
  Forks: number;
  OpenIssues: number;
}

// Wails bindings — these will be generated by wails generate module
// For now we define the interface manually
declare global {
  interface Window {
    Go: {
      main: {
        App: {
          GetStatus(): Promise<Status>;
          GetLog(count: number): Promise<Commit[]>;
          GetBranches(): Promise<Branch[]>;
          GetDiff(pathspec: string): Promise<Diff>;
          StageFile(file: string): Promise<void>;
          UnstageFile(file: string): Promise<void>;
          StageAll(): Promise<void>;
          UnstageAll(): Promise<void>;
          Commit(message: string): Promise<string>;
          CheckoutBranch(name: string): Promise<void>;
          CreateBranch(name: string): Promise<void>;
          DeleteBranch(name: string, force: boolean): Promise<void>;
          CurrentBranch(): Promise<string>;
          IsGitHubAuthenticated(): Promise<boolean>;
          GetPullRequests(): Promise<PRSummary[]>;
          GetIssues(): Promise<Issue[]>;
          GetRepository(): Promise<Repo>;
          GetCurrentRepoPath(): Promise<string>;
          GetGitHubUser(): Promise<{ Login: string; Name: string; AvatarURL: string }>;
        };
      };
    };
  }
}

// App state store
interface AppState {
  // Git state
  status: Status | null;
  log: Commit[];
  branches: Branch[];
  diff: Diff | null;
  currentBranch: string;

  // GitHub state
  ghAuthenticated: boolean;
  ghUser: { Login: string; Name: string; AvatarURL: string } | null;
  pullRequests: PRSummary[];
  issues: Issue[];
  repository: Repo | null;

  // UI state
  loading: Record<string, boolean>;
  error: string | null;
  activeTab: string;
  darkMode: boolean;

  // Actions
  setActiveTab: (tab: string) => void;
  toggleDarkMode: () => void;
  fetchStatus: () => Promise<void>;
  fetchLog: (count?: number) => Promise<void>;
  fetchBranches: () => Promise<void>;
  fetchDiff: (pathspec?: string) => Promise<void>;
  stageFile: (file: string) => Promise<void>;
  unstageFile: (file: string) => Promise<void>;
  stageAll: () => Promise<void>;
  unstageAll: () => Promise<void>;
  commit: (message: string) => Promise<string | null>;
  checkoutBranch: (name: string) => Promise<void>;
  createBranch: (name: string) => Promise<void>;
  deleteBranch: (name: string, force?: boolean) => Promise<void>;
  fetchPullRequests: () => Promise<void>;
  fetchIssues: () => Promise<void>;
  fetchRepository: () => Promise<void>;
  checkGitHubAuth: () => Promise<void>;
  setError: (err: string | null) => void;
  clearDiff: () => void;
}

const app = window as any;

function getBackend() {
  // During development with wails dev, the backend is at window.go.main.App
  // During standalone, we construct from window.Go.main.App
  return app.go?.main?.App || app.Go?.main?.App || null;
}

export const useAppStore = create<AppState>((set, get) => ({
  // Initial state
  status: null,
  log: [],
  branches: [],
  diff: null,
  currentBranch: "",
  ghAuthenticated: false,
  ghUser: null,
  pullRequests: [],
  issues: [],
  repository: null,
  loading: {},
  error: null,
  activeTab: "status",
  darkMode: true,

  setActiveTab: (tab) => set({ activeTab: tab }),

  toggleDarkMode: () => {
    const next = !get().darkMode;
    document.documentElement.classList.toggle("dark", next);
    set({ darkMode: next });
  },

  fetchStatus: async () => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, status: true }, error: null }));
    try {
      const status = await backend.GetStatus();
      set({ status, loading: { ...get().loading, status: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch status", loading: { ...get().loading, status: false } });
    }
  },

  fetchLog: async (count = 50) => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, log: true } }));
    try {
      const log = await backend.GetLog(count);
      set({ log, loading: { ...get().loading, log: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch log", loading: { ...get().loading, log: false } });
    }
  },

  fetchBranches: async () => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, branches: true } }));
    try {
      const [branches, currentBranch] = await Promise.all([
        backend.GetBranches(),
        backend.CurrentBranch(),
      ]);
      set({ branches, currentBranch, loading: { ...get().loading, branches: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch branches", loading: { ...get().loading, branches: false } });
    }
  },

  fetchDiff: async (pathspec = "") => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, diff: true } }));
    try {
      const diff = await backend.GetDiff(pathspec);
      set({ diff, loading: { ...get().loading, diff: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch diff", loading: { ...get().loading, diff: false } });
    }
  },

  stageFile: async (file) => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.StageFile(file);
      await get().fetchStatus();
    } catch (e: any) {
      set({ error: e.message || "Failed to stage file" });
    }
  },

  unstageFile: async (file) => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.UnstageFile(file);
      await get().fetchStatus();
    } catch (e: any) {
      set({ error: e.message || "Failed to unstage file" });
    }
  },

  stageAll: async () => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.StageAll();
      await get().fetchStatus();
    } catch (e: any) {
      set({ error: e.message || "Failed to stage all" });
    }
  },

  unstageAll: async () => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.UnstageAll();
      await get().fetchStatus();
    } catch (e: any) {
      set({ error: e.message || "Failed to unstage all" });
    }
  },

  commit: async (message) => {
    const backend = getBackend();
    if (!backend) return null;
    try {
      const hash = await backend.Commit(message);
      await get().fetchStatus();
      await get().fetchLog();
      return hash;
    } catch (e: any) {
      set({ error: e.message || "Failed to commit" });
      return null;
    }
  },

  checkoutBranch: async (name) => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.CheckoutBranch(name);
      await Promise.all([get().fetchStatus(), get().fetchBranches()]);
      set({ diff: null });
    } catch (e: any) {
      set({ error: e.message || `Failed to checkout ${name}` });
    }
  },

  createBranch: async (name) => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.CreateBranch(name);
      await get().fetchBranches();
    } catch (e: any) {
      set({ error: e.message || `Failed to create branch ${name}` });
    }
  },

  deleteBranch: async (name, force = false) => {
    const backend = getBackend();
    if (!backend) return;
    try {
      await backend.DeleteBranch(name, force);
      await get().fetchBranches();
    } catch (e: any) {
      set({ error: e.message || `Failed to delete branch ${name}` });
    }
  },

  fetchPullRequests: async () => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, prs: true } }));
    try {
      const prs = await backend.GetPullRequests();
      set({ pullRequests: prs, loading: { ...get().loading, prs: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch PRs", loading: { ...get().loading, prs: false } });
    }
  },

  fetchIssues: async () => {
    const backend = getBackend();
    if (!backend) return;
    set((s) => ({ loading: { ...s.loading, issues: true } }));
    try {
      const issues = await backend.GetIssues();
      set({ issues, loading: { ...get().loading, issues: false } });
    } catch (e: any) {
      set({ error: e.message || "Failed to fetch issues", loading: { ...get().loading, issues: false } });
    }
  },

  fetchRepository: async () => {
    const backend = getBackend();
    if (!backend) return;
    try {
      const repo = await backend.GetRepository();
      set({ repository: repo });
    } catch (_) {
      // Non-critical
    }
  },

  checkGitHubAuth: async () => {
    const backend = getBackend();
    if (!backend) return;
    try {
      const authed = await backend.IsGitHubAuthenticated();
      set({ ghAuthenticated: authed });
      if (authed) {
        const user = await backend.GetGitHubUser();
        set({ ghUser: user });
      }
    } catch (_) {
      set({ ghAuthenticated: false });
    }
  },

  setError: (err) => set({ error: err }),
  clearDiff: () => set({ diff: null }),
}));
