// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {models} from '../models';
import {embed} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function AgentApproveProposal(arg1:string):Promise<ai.ProposalResult>;

export function AgentCancel():Promise<void>;

export function AgentChat(arg1:string):Promise<ai.AgentResponse>;

export function AgentGetHistory():Promise<Array<ai.Message>>;

export function AgentGetProposals():Promise<Array<ai.AgentActionProposal>>;

export function AgentRejectProposal(arg1:string,arg2:string):Promise<void>;

export function AgentReset():Promise<void>;

export function AgentStart():Promise<void>;

export function AskChat(arg1:string):Promise<string>;

export function AskChatCancel():Promise<void>;

export function AskChatStream(arg1:string):Promise<void>;

export function AuthenticateGitHub(arg1:string):Promise<void>;

export function CancelWorkflowRun(arg1:number):Promise<void>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function CheckoutOurs(arg1:string):Promise<void>;

export function CheckoutTheirs(arg1:string):Promise<void>;

export function CherryPick(arg1:string):Promise<void>;

export function CloseIssue(arg1:number):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<string>;

export function ConfigGet(arg1:string):Promise<string>;

export function ConfigSet(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreateIssue(arg1:string,arg2:string):Promise<models.Issue>;

export function CreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<models.PullRequestSummary>;

export function CurrentBranch():Promise<string>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function DiscardAllFiles():Promise<void>;

export function DiscardFile(arg1:string):Promise<void>;

export function GenerateCommitMessage():Promise<string>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetAheadCommits():Promise<Array<models.Commit>>;

export function GetBranches():Promise<Array<models.Branch>>;

export function GetConflictFiles():Promise<Array<models.ConflictFile>>;

export function GetCurrentRepoPath():Promise<string>;

export function GetDiff(arg1:string):Promise<models.Diff>;

export function GetFileDiff(arg1:string):Promise<models.Diff>;

export function GetGitHubUser():Promise<models.User>;

export function GetGraphLog(arg1:number):Promise<Array<models.Commit>>;

export function GetIssueDetail(arg1:number):Promise<models.Issue>;

export function GetIssues():Promise<Array<models.Issue>>;

export function GetLog(arg1:number):Promise<Array<models.Commit>>;

export function GetMergeConflictDetail(arg1:string):Promise<models.MergeConflictDetail>;

export function GetPullRequestDetail(arg1:number):Promise<models.PullRequestDetail>;

export function GetPullRequests():Promise<Array<models.PullRequestSummary>>;

export function GetReflog(arg1:number):Promise<Array<models.ReflogEntry>>;

export function GetRemotes():Promise<Array<models.Remote>>;

export function GetRepoName():Promise<string>;

export function GetRepoPath():Promise<string>;

export function GetRepository():Promise<models.Repo>;

export function GetStatus():Promise<models.Status>;

export function GetWorkflowJobLogs(arg1:number):Promise<string>;

export function GitFetch():Promise<void>;

export function GitMerge(arg1:string):Promise<string>;

export function GitPull(arg1:boolean):Promise<void>;

export function GitPush():Promise<void>;

export function GitPushForce():Promise<void>;

export function GitRenameBranch(arg1:string,arg2:string):Promise<void>;

export function IsGitHubAuthenticated():Promise<boolean>;

export function ListRecentRepos():Promise<Array<string>>;

export function ListWorkflowJobs(arg1:number):Promise<Array<models.Job>>;

export function ListWorkflowRuns():Promise<Array<models.WorkflowRun>>;

export function MergePullRequest(arg1:number,arg2:string):Promise<void>;

export function OpenRepo(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PollDeviceFlow(arg1:string):Promise<string>;

export function ReRunWorkflow(arg1:number):Promise<void>;

export function RebaseSequence(arg1:string,arg2:string):Promise<models.RebaseResult>;

export function RemoveRemote(arg1:string):Promise<void>;

export function ResetCommit(arg1:string,arg2:string):Promise<void>;

export function ResolveGitRoot(arg1:string):Promise<string>;

export function RevertCommit(arg1:string):Promise<void>;

export function Run(arg1:embed.FS):Promise<void>;

export function SessionActiveID():Promise<string>;

export function SessionClearMessages(arg1:string):Promise<void>;

export function SessionCreate(arg1:string,arg2:string):Promise<ai.SessionSummary>;

export function SessionDelete(arg1:string):Promise<void>;

export function SessionGetMessages(arg1:string):Promise<Array<ai.Message>>;

export function SessionList():Promise<Array<ai.SessionSummary>>;

export function SessionRename(arg1:string,arg2:string):Promise<void>;

export function SessionSwitch(arg1:string):Promise<ai.SessionSummary>;

export function SetAIConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function StagePatch(arg1:string):Promise<void>;

export function StageResolvedFile(arg1:string,arg2:string):Promise<void>;

export function StartDeviceFlow():Promise<models.DeviceFlowCode>;

export function StashApply(arg1:number):Promise<void>;

export function StashDrop(arg1:number):Promise<void>;

export function StashList():Promise<Array<models.Stash>>;

export function StashPop(arg1:number):Promise<void>;

export function StashPush(arg1:string):Promise<void>;

export function TagCreate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TagDelete(arg1:string):Promise<void>;

export function TagList():Promise<Array<string>>;

export function UndoLastAction():Promise<string>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;
