// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {embed} from '../models';

export function AuthenticateGitHub(arg1:string):Promise<void>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<string>;

export function CreateBranch(arg1:string):Promise<void>;

export function CurrentBranch():Promise<string>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function GetBranches():Promise<Array<models.Branch>>;

export function GetCurrentRepoPath():Promise<string>;

export function GetDiff(arg1:string):Promise<models.Diff>;

export function GetFileDiff(arg1:string):Promise<models.Diff>;

export function GetGitHubUser():Promise<models.User>;

export function GetIssues():Promise<Array<models.Issue>>;

export function GetLog(arg1:number):Promise<Array<models.Commit>>;

export function GetPullRequests():Promise<Array<models.PullRequestSummary>>;

export function GetRepository():Promise<models.Repo>;

export function GetStatus():Promise<models.Status>;

export function IsGitHubAuthenticated():Promise<boolean>;

export function Run(arg1:embed.FS):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;
