// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateGitHub(arg1) {
  return window['go']['main']['App']['AuthenticateGitHub'](arg1);
}

export function CancelWorkflowRun(arg1) {
  return window['go']['main']['App']['CancelWorkflowRun'](arg1);
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CurrentBranch() {
  return window['go']['main']['App']['CurrentBranch']();
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function DiscardAllFiles() {
  return window['go']['main']['App']['DiscardAllFiles']();
}

export function DiscardFile(arg1) {
  return window['go']['main']['App']['DiscardFile'](arg1);
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCurrentRepoPath() {
  return window['go']['main']['App']['GetCurrentRepoPath']();
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetGitHubUser() {
  return window['go']['main']['App']['GetGitHubUser']();
}

export function GetIssues() {
  return window['go']['main']['App']['GetIssues']();
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetPullRequests() {
  return window['go']['main']['App']['GetPullRequests']();
}

export function GetRepoName() {
  return window['go']['main']['App']['GetRepoName']();
}

export function GetRepoPath() {
  return window['go']['main']['App']['GetRepoPath']();
}

export function GetRepository() {
  return window['go']['main']['App']['GetRepository']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetWorkflowJobLogs(arg1) {
  return window['go']['main']['App']['GetWorkflowJobLogs'](arg1);
}

export function GitFetch() {
  return window['go']['main']['App']['GitFetch']();
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitPushForce() {
  return window['go']['main']['App']['GitPushForce']();
}

export function IsGitHubAuthenticated() {
  return window['go']['main']['App']['IsGitHubAuthenticated']();
}

export function ListRecentRepos() {
  return window['go']['main']['App']['ListRecentRepos']();
}

export function ListWorkflowJobs(arg1) {
  return window['go']['main']['App']['ListWorkflowJobs'](arg1);
}

export function ListWorkflowRuns() {
  return window['go']['main']['App']['ListWorkflowRuns']();
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PollDeviceFlow(arg1) {
  return window['go']['main']['App']['PollDeviceFlow'](arg1);
}

export function ReRunWorkflow(arg1) {
  return window['go']['main']['App']['ReRunWorkflow'](arg1);
}

export function ResolveGitRoot(arg1) {
  return window['go']['main']['App']['ResolveGitRoot'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}

export function StashApply(arg1) {
  return window['go']['main']['App']['StashApply'](arg1);
}

export function StashDrop(arg1) {
  return window['go']['main']['App']['StashDrop'](arg1);
}

export function StashList() {
  return window['go']['main']['App']['StashList']();
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function StashPush(arg1) {
  return window['go']['main']['App']['StashPush'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}
