// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {embed} from '../models';

export function AuthenticateGitHub(arg1:string):Promise<void>;

export function CancelWorkflowRun(arg1:number):Promise<void>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<string>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<models.PullRequestSummary>;

export function CurrentBranch():Promise<string>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function DiscardAllFiles():Promise<void>;

export function DiscardFile(arg1:string):Promise<void>;

export function GetBranches():Promise<Array<models.Branch>>;

export function GetCurrentRepoPath():Promise<string>;

export function GetDiff(arg1:string):Promise<models.Diff>;

export function GetFileDiff(arg1:string):Promise<models.Diff>;

export function GetGitHubUser():Promise<models.User>;

export function GetIssues():Promise<Array<models.Issue>>;

export function GetLog(arg1:number):Promise<Array<models.Commit>>;

export function GetPullRequestDetail(arg1:number):Promise<models.PullRequestDetail>;

export function GetPullRequests():Promise<Array<models.PullRequestSummary>>;

export function GetRepoName():Promise<string>;

export function GetRepoPath():Promise<string>;

export function GetRepository():Promise<models.Repo>;

export function GetStatus():Promise<models.Status>;

export function GetWorkflowJobLogs(arg1:number):Promise<string>;

export function GitFetch():Promise<void>;

export function GitMerge(arg1:string):Promise<string>;

export function GitPull(arg1:boolean):Promise<void>;

export function GitPush():Promise<void>;

export function GitPushForce():Promise<void>;

export function GitRenameBranch(arg1:string,arg2:string):Promise<void>;

export function IsGitHubAuthenticated():Promise<boolean>;

export function ListRecentRepos():Promise<Array<string>>;

export function ListWorkflowJobs(arg1:number):Promise<Array<models.Job>>;

export function ListWorkflowRuns():Promise<Array<models.WorkflowRun>>;

export function MergePullRequest(arg1:number,arg2:string):Promise<void>;

export function OpenRepo(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PollDeviceFlow(arg1:string):Promise<string>;

export function ReRunWorkflow(arg1:number):Promise<void>;

export function ResolveGitRoot(arg1:string):Promise<string>;

export function Run(arg1:embed.FS):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function StartDeviceFlow():Promise<models.DeviceFlowCode>;

export function StashApply(arg1:number):Promise<void>;

export function StashDrop(arg1:number):Promise<void>;

export function StashList():Promise<Array<models.Stash>>;

export function StashPop(arg1:number):Promise<void>;

export function StashPush(arg1:string):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;
