// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2) {
  return window['go']['main']['App']['AddRemote'](arg1, arg2);
}

export function AgentApproveProposal(arg1) {
  return window['go']['main']['App']['AgentApproveProposal'](arg1);
}

export function AgentCancel() {
  return window['go']['main']['App']['AgentCancel']();
}

export function AgentChat(arg1) {
  return window['go']['main']['App']['AgentChat'](arg1);
}

export function AgentGetHistory() {
  return window['go']['main']['App']['AgentGetHistory']();
}

export function AgentGetProposals() {
  return window['go']['main']['App']['AgentGetProposals']();
}

export function AgentRejectProposal(arg1, arg2) {
  return window['go']['main']['App']['AgentRejectProposal'](arg1, arg2);
}

export function AgentReset() {
  return window['go']['main']['App']['AgentReset']();
}

export function AgentStart() {
  return window['go']['main']['App']['AgentStart']();
}

export function AskChat(arg1) {
  return window['go']['main']['App']['AskChat'](arg1);
}

export function AskChatCancel() {
  return window['go']['main']['App']['AskChatCancel']();
}

export function AskChatStream(arg1) {
  return window['go']['main']['App']['AskChatStream'](arg1);
}

export function AuthenticateGitHub(arg1) {
  return window['go']['main']['App']['AuthenticateGitHub'](arg1);
}

export function CancelDeviceFlow() {
  return window['go']['main']['App']['CancelDeviceFlow']();
}

export function CancelWorkflowRun(arg1) {
  return window['go']['main']['App']['CancelWorkflowRun'](arg1);
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function CheckoutOurs(arg1) {
  return window['go']['main']['App']['CheckoutOurs'](arg1);
}

export function CheckoutTheirs(arg1) {
  return window['go']['main']['App']['CheckoutTheirs'](arg1);
}

export function CherryPick(arg1) {
  return window['go']['main']['App']['CherryPick'](arg1);
}

export function CloseIssue(arg1) {
  return window['go']['main']['App']['CloseIssue'](arg1);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function ConfigGet(arg1) {
  return window['go']['main']['App']['ConfigGet'](arg1);
}

export function ConfigSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfigSet'](arg1, arg2, arg3);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateIssue(arg1, arg2) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2);
}

export function CreatePullRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePullRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function CurrentBranch() {
  return window['go']['main']['App']['CurrentBranch']();
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function DiscardAllFiles() {
  return window['go']['main']['App']['DiscardAllFiles']();
}

export function DiscardFile(arg1) {
  return window['go']['main']['App']['DiscardFile'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['main']['App']['GenerateCommitMessage']();
}

export function GeneratePRDescription(arg1, arg2) {
  return window['go']['main']['App']['GeneratePRDescription'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAheadCommits() {
  return window['go']['main']['App']['GetAheadCommits']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetConflictFiles() {
  return window['go']['main']['App']['GetConflictFiles']();
}

export function GetCurrentRepoPath() {
  return window['go']['main']['App']['GetCurrentRepoPath']();
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetGitHubUser() {
  return window['go']['main']['App']['GetGitHubUser']();
}

export function GetGraphLog(arg1) {
  return window['go']['main']['App']['GetGraphLog'](arg1);
}

export function GetIssueDetail(arg1) {
  return window['go']['main']['App']['GetIssueDetail'](arg1);
}

export function GetIssues() {
  return window['go']['main']['App']['GetIssues']();
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetMergeConflictDetail(arg1) {
  return window['go']['main']['App']['GetMergeConflictDetail'](arg1);
}

export function GetPullRequestDetail(arg1) {
  return window['go']['main']['App']['GetPullRequestDetail'](arg1);
}

export function GetPullRequests() {
  return window['go']['main']['App']['GetPullRequests']();
}

export function GetReflog(arg1) {
  return window['go']['main']['App']['GetReflog'](arg1);
}

export function GetRemotes() {
  return window['go']['main']['App']['GetRemotes']();
}

export function GetRepoName() {
  return window['go']['main']['App']['GetRepoName']();
}

export function GetRepoPath() {
  return window['go']['main']['App']['GetRepoPath']();
}

export function GetRepository() {
  return window['go']['main']['App']['GetRepository']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUserPreferences() {
  return window['go']['main']['App']['GetUserPreferences']();
}

export function GetWorkflowJobLogs(arg1) {
  return window['go']['main']['App']['GetWorkflowJobLogs'](arg1);
}

export function GitFetch() {
  return window['go']['main']['App']['GitFetch']();
}

export function GitMerge(arg1) {
  return window['go']['main']['App']['GitMerge'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitPushForce() {
  return window['go']['main']['App']['GitPushForce']();
}

export function GitRenameBranch(arg1, arg2) {
  return window['go']['main']['App']['GitRenameBranch'](arg1, arg2);
}

export function IsGitHubAuthenticated() {
  return window['go']['main']['App']['IsGitHubAuthenticated']();
}

export function ListRecentRepos() {
  return window['go']['main']['App']['ListRecentRepos']();
}

export function ListWorkflowJobs(arg1) {
  return window['go']['main']['App']['ListWorkflowJobs'](arg1);
}

export function ListWorkflowRuns() {
  return window['go']['main']['App']['ListWorkflowRuns']();
}

export function LogoutGitHub() {
  return window['go']['main']['App']['LogoutGitHub']();
}

export function MergePullRequest(arg1, arg2) {
  return window['go']['main']['App']['MergePullRequest'](arg1, arg2);
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PollDeviceFlow(arg1) {
  return window['go']['main']['App']['PollDeviceFlow'](arg1);
}

export function PollDeviceFlowWithRetry(arg1, arg2) {
  return window['go']['main']['App']['PollDeviceFlowWithRetry'](arg1, arg2);
}

export function ReRunWorkflow(arg1) {
  return window['go']['main']['App']['ReRunWorkflow'](arg1);
}

export function RebaseSequence(arg1, arg2) {
  return window['go']['main']['App']['RebaseSequence'](arg1, arg2);
}

export function RemoveRemote(arg1) {
  return window['go']['main']['App']['RemoveRemote'](arg1);
}

export function RenameRemote(arg1, arg2) {
  return window['go']['main']['App']['RenameRemote'](arg1, arg2);
}

export function ResetCommit(arg1, arg2) {
  return window['go']['main']['App']['ResetCommit'](arg1, arg2);
}

export function ResolveGitRoot(arg1) {
  return window['go']['main']['App']['ResolveGitRoot'](arg1);
}

export function RevertCommit(arg1) {
  return window['go']['main']['App']['RevertCommit'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SaveGitHubToken(arg1) {
  return window['go']['main']['App']['SaveGitHubToken'](arg1);
}

export function SessionActiveID() {
  return window['go']['main']['App']['SessionActiveID']();
}

export function SessionClearMessages(arg1) {
  return window['go']['main']['App']['SessionClearMessages'](arg1);
}

export function SessionCreate(arg1, arg2) {
  return window['go']['main']['App']['SessionCreate'](arg1, arg2);
}

export function SessionDelete(arg1) {
  return window['go']['main']['App']['SessionDelete'](arg1);
}

export function SessionGetMessages(arg1) {
  return window['go']['main']['App']['SessionGetMessages'](arg1);
}

export function SessionList() {
  return window['go']['main']['App']['SessionList']();
}

export function SessionRename(arg1, arg2) {
  return window['go']['main']['App']['SessionRename'](arg1, arg2);
}

export function SessionSwitch(arg1) {
  return window['go']['main']['App']['SessionSwitch'](arg1);
}

export function SetAIConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAIConfig'](arg1, arg2, arg3, arg4);
}

export function SetRemoteURL(arg1, arg2) {
  return window['go']['main']['App']['SetRemoteURL'](arg1, arg2);
}

export function SetUserPreferences(arg1) {
  return window['go']['main']['App']['SetUserPreferences'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function StagePatch(arg1) {
  return window['go']['main']['App']['StagePatch'](arg1);
}

export function StageResolvedFile(arg1, arg2) {
  return window['go']['main']['App']['StageResolvedFile'](arg1, arg2);
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}

export function StashApply(arg1) {
  return window['go']['main']['App']['StashApply'](arg1);
}

export function StashDrop(arg1) {
  return window['go']['main']['App']['StashDrop'](arg1);
}

export function StashList() {
  return window['go']['main']['App']['StashList']();
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function StashPush(arg1) {
  return window['go']['main']['App']['StashPush'](arg1);
}

export function TagCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['TagCreate'](arg1, arg2, arg3);
}

export function TagDelete(arg1) {
  return window['go']['main']['App']['TagDelete'](arg1);
}

export function TagList() {
  return window['go']['main']['App']['TagList']();
}

export function UndoLastAction() {
  return window['go']['main']['App']['UndoLastAction']();
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}

export function ValidateGitHubToken() {
  return window['go']['main']['App']['ValidateGitHubToken']();
}
