// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateGitHub(arg1) {
  return window['go']['main']['App']['AuthenticateGitHub'](arg1);
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CurrentBranch() {
  return window['go']['main']['App']['CurrentBranch']();
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCurrentRepoPath() {
  return window['go']['main']['App']['GetCurrentRepoPath']();
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetGitHubUser() {
  return window['go']['main']['App']['GetGitHubUser']();
}

export function GetIssues() {
  return window['go']['main']['App']['GetIssues']();
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetPullRequests() {
  return window['go']['main']['App']['GetPullRequests']();
}

export function GetRepository() {
  return window['go']['main']['App']['GetRepository']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsGitHubAuthenticated() {
  return window['go']['main']['App']['IsGitHubAuthenticated']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}
